### ISSUE TITLE
Table Creation

### ISSUE THREAD

**Issue by damiangreen** [feinoujc/Elmah.DynamoDB#1]
Does the table need to be pre-created? What is the Hash key name?. Does it use the _AWS.DynamoDBContext.TableNamePrefix_ key from appsettings?

I've tried both and don't see an error logged.

After looking at the code it appears  that it may be caused at 
`at Elmah.DynamoDB.DynamoDBErrorLog.GetClient(IDictionary configuration)`

I currently create a conenction to DynamoDb in my app

```
   public AmazonDynamoDBClient GetAmazonDynamoDbClient()
        {
            return string.IsNullOrWhiteSpace(Configuration.S3AccessKey) ? new AmazonDynamoDBClient(new AmazonDynamoDBConfig { ServiceURL = "http://dynamodb.eu-west-1.amazonaws.com" }) : new AmazonDynamoDBClient(Configuration.S3AccessKey, Configuration.S3SecretKey, Configuration.AwsRegion);
        }
```

I notice there is a public constructor in your code which  receives an AmazonDynamoDBClient. Do you know how I  invoke this?

**Comment by feinoujc** [comment]
@damiangreen apologies, I somehow missed this question.

One option if you want to control the AmazonDynamoDBClient instance would be to configure Elmah in code.

you would need to run this during your application startup:

``` cs
    public static class ElmahConfig
    {
        public static void Start()
        {
            ServiceCenter.Current = CreateServiceProviderQueryHandler(ServiceCenter.Current);
        }

        private static ServiceProviderQueryHandler CreateServiceProviderQueryHandler(ServiceProviderQueryHandler sp)
        {
            return context =>
            {
                var container = new ServiceContainer(sp(context));

                var log = new DynamoDBErrorLog(new AmazonDynamoDBClient( /*construct how you want here*/),
                        "my-application-name-here");

                container.AddService(typeof(ErrorLog), log);
                return container;
            };
        }
    }
```

Then you no longer need the errorLog element in your config

``` xml
<errorLog type="Elmah.DynamoDB.DynamoDBErrorLog, Elmah.DynamoDB" applicationName="MvcSample"... />
```

As for table creation, yes it should create the table if it doesn't exist, but keep in mind that IAM identity does need the appropriate permissions to do so
